

---

What relationship do we expect between practice and performance? 4

```{r}
idealised_example_data = tibble(
  x=c(0, 12),
  y=c(25, 96.61)
)

ggplot(example_data, aes(y=accuracy_Asian, x=duration_SEA))+
  theme_apa()+theme(axis.title.y = element_text(angle = 0, hjust = 0.5, vjust=0.5))+
  scale_x_continuous(limits=c(0, 12), breaks=seq(0, 12, 4)) +
  scale_y_continuous(limits=c(25, 100), breaks=seq(25, 100, 25))+
  geom_smooth(data=idealised_example_data, aes(x=x, y=y), se=F, method='lm')

```


---

What relationship do we actually get between practice and performance? (for data similar to the assignment data)


```{r}
ggplot(example_data, aes(y=accuracy_Asian, x=duration_SEA))+
  theme_apa()+theme(axis.title.y = element_text(angle = 0, hjust = 0.5, vjust=0.5))+
  scale_x_continuous(limits=c(min(example_data$duration_SEA), max(example_data$duration_SEA)), breaks=seq(0, 12, 4)) +
  scale_y_continuous(limits=c(min(example_data$accuracy_Asian), 100), breaks=seq(25, 100, 25)) +
  geom_point()+
  geom_smooth(se=F, method='lm')
```

